language: python

matrix:
    include:
        - python: 2.6
          os: linux
          dist: trusty
          env: TOXENV=py26
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27
        - python: pypy
          os: linux
          dist: trusty
          env: TOXENV=pypy
        - python: 3.3
          os: linux
          dist: trusty
          env: TOXENV=py33
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=py37

# command to install dependencies
install:
  - "pip install ."

# command to run tests
script: nosetests
